name: CI & Deployment

on:
  push:
    branches: [ "1.21.1" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish to Snapshots Maven
        env:
          KRYSTAL_MAVEN_USER: ${{ secrets.KRYSTAL_MAVEN_USER }}
          KRYSTAL_MAVEN_PASSWORD: ${{ secrets.KRYSTAL_MAVEN_TOKEN }}
          KRYSTAL_MAVEN_TOKEN: ${{ secrets.KRYSTAL_MAVEN_TOKEN }}
        run: ./gradlew publish -Psnapshot_versioning=true -PkrystalRepository=snapshots
